# Generated by Django 2.2.2 on 2019-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='usuario/imagenes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
