# Generated by Django 2.2.2 on 2019-08-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rol_permiso'),
        ('proyectos', '0002_auto_20190815_2330'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='proyecto_involucrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Rol'),
        ),
    ]
