# Generated by Django 2.2.2 on 2019-08-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('lineasBase', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='linea_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineasBase.LineaBase'),
        ),
        migrations.AddField(
            model_name='item',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil'),
        ),
    ]
