# Generated by Django 2.2.2 on 2019-08-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('lineasBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
    ]
